# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='users',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
